<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>demo-cura</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b65995f7-e822-42e7-9bd3-8070d9d84138</testSuiteGuid>
   <testCaseLink>
      <guid>7f00c6b4-7b85-4576-8ebe-c180ef259db9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/1. User input correct username and correct password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc2d4cd-6911-4098-bfa3-f5a5157d47ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74423132-7a5a-40fb-9333-3aaa6a11bcf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>997be7c4-517a-49f0-ae44-156da111c027</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/2. User input username field and doesnt input password field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>723be4f8-a81f-4a90-94fd-266b1cdc7e12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc1c81f6-ea96-4937-92ef-c4db5702d472</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75c6b222-6e9c-416e-9f5d-56f7bb6314a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/3. User doesnt input username field and input password field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ed2a06-ebac-4c4f-a640-54839c5416f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4f9ae14-59a7-44cb-bafc-2ccaa242c7f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>807cc929-3e69-46c0-828d-0c5bea8eceb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/4. User doesnt input username and password field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5604507-c28c-4c74-9bc6-f96247ddc24c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>124892c8-6d01-4827-b286-a1f30cc73d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bb0c584-f6fa-41ee-8b9a-f499f5c93be2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/5. User input correct username and incorrect password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a9be8d7-db4a-4ea0-8e3b-d88d0145f85a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca8e6cf5-cebb-4a53-b41f-96d30aaed8e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d94c250a-81d2-4658-a717-2e06c7adb8ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/6. User input incorrect username and correct password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4276061-9960-4f8e-8fbc-5d1cf9194a5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4d56943-bafd-42e2-89b4-6b8bdcf06169</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c29d2ce3-7b46-48c6-a0c4-2ebccfefc201</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/7. User input incorrect username and incorrect password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82356270-ce19-4ef7-84ca-ccbf4b4c3f53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba7f8939-3187-49ec-9cdb-d7fca6e7472b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0ba6b33-eed8-4f11-bfa5-51b14701b266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Logout/8. User click logout button from hamburger menu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ee25be5-1b83-4fc8-b52a-2d7a3477f9f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b9100c-7453-476a-a62d-ac7571ae731d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4158a609-50dc-499b-be02-0a89dfe08100</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/9. User input all required field to make appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d9c0a45e-1520-4826-b18c-ccf2e5286162</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/10. User doesnt input the required field to make appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1108018d-f929-400b-af65-ce10bb26eba5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Make Appointment/11. User want to make appointment without login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
